import{a as $,i as p,S as q}from"./assets/vendor-DEenWwFD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&y(n)}).observe(document,{childList:!0,subtree:!0});function c(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function y(t){if(t.ep)return;t.ep=!0;const o=c(t);fetch(t.href,o)}})();document.querySelector(".list");function v(e){return e.map(w).join("")}function w(e){return`
    <li class='elem-list'>
        <div class="gallery">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" loading="lazy" alt="${e.tags}" title="${e.tags}" class='image'/>
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </div>
        </li>`}const i=document.querySelector(".loader"),h=document.querySelector(".list"),u=document.querySelector(".btn-more");u.style.display="none";i&&(i.style.display="none");const M="48878518-9063069941d99e969b9b19843",P="https://pixabay.com/api/";async function L(e,s=1,c=20,y=!1){i&&(i.style.display="");const t=`${P}?key=${M}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${c}&page=${s}`;try{const n=(await $.get(t)).data;if(i&&(i.style.display="none"),!n.hits||n.hits.length===0){u.style.display="none",p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});return}else{const f=v(n.hits);y?h.insertAdjacentHTML("beforeend",f):h.innerHTML=f,u.style.display=""}return n}catch(o){u.style.display="none",p.error({message:o.message,timeout:5e3,position:"topRight"}),i&&(i.style.display="none")}}const g=document.querySelector("#text"),b=document.querySelector(".list"),R=document.querySelector(".search"),l=document.querySelector(".loader"),r=document.querySelector(".btn-more");r.style.display="none";l.style.display="none";let d=1,m=15,a="",S=new q(".list a",{captions:!0,captionsData:"alt",captionDelay:250,animationSlide:!0});g.addEventListener("input",e=>{a=e.target.value,a.trim()===""&&(g.value="")});R.addEventListener("click",async e=>{if(e.preventDefault(),d=1,d===1&&(r.style.display="none"),a=g.value.trim(),!a||a.trim()==="")return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});b.innerHTML="";try{l.style.display="";const s=await L(a,d,m);if(l.style.display="none",!s.hits||s.hits.length===0)return p.error({message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,position:"topRight"});b.innerHTML=v(s.hits),S.refresh(),Math.ceil(s.totalHits/m)<=1?r.style.display="none":r.style.display=""}catch{l.style.display="none";return}});r.addEventListener("click",async()=>{d+=1,l.style.display="",r.style.display="none";try{const e=await L(a,d,m,!0);l.style.display="none",S.refresh();const s=document.querySelector(".list li");if(s){const y=s.getBoundingClientRect().height;window.scrollBy({top:y*2,behavior:"smooth"})}const c=Math.ceil(e.totalHits/m);d>=c?(r.style.display="none",p.info({position:"topRight",message:"You've reached the end of the results"})):r.style.display=""}catch{l.style.display="none",r.style.display="none"}});
//# sourceMappingURL=index.js.map
